{
    'name': 'Allied Report',
    'category': 'Allied Reports',
    'summary': 'Hidden',
    'version': '1.0',
    'description': """
Allied Reports
        """,
    'depends': ['bista_allied_purchase_barcode_slip',
                'purchase', 'web', 'sale', 'delivery',
                'allied_landed_cost', 'account_reports', 'base_vat', 'delivery', 'report_xls', 'bista_allied_fields',
                'stock_picking_invoice_link',
                ],
    'data': [
             'view/allied_bill_of_lading_sequence.xml',
             'view/allied_bill_of_lading_view.xml',
             'view/allied_extra_fields.xml',
             'report/qweb_report.xml',
             # 'report/allied_purchase_order_report_template.xml',
             'report/consignment_order_report_view.xml',
             'report/purchase_order_report_view.xml',
             'report/allied_sale_order_report_template.xml',
             'report/allied_sale_order_invoice_report_template.xml',
             'report/allied_delivery_report_template.xml',
             'report/customer_ack_report_template.xml',
             # 'report/pack_slip_report_template.xml',
             'report/picking_ticket_report_template.xml',
             'report/extra_fields_inherit.xml',
             # 'report/simplified_sale_order_report.xml',
             'report/straight_bill_of_lading_template.xml',
             'report/report_layout.xml',
             'data/allied_financial_statement_report.xml',
             'data/allied_financial_balace_sheet_report.xml',
             'data/allied_selling_expense_report.xml',
             'data/allied_general_admin_exp.xml',
             'data/allied_shop_expense.xml',
             'wizard/product_family_view.xml',
             'report/pack_slip_template.xml',
             'report/packing_operations_inherit_report.xml',
             'report/allied_sale_order_quotation_report_template.xml',
             'report/report_financial.xml',
             'view/report_financial.xml',
             ],
    'installable': True,
    'auto_install': False,
}
